global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "api-gateway"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8080"]
  - job_name: "resource-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["resource-service:8081"]
  - job_name: "booking-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["booking-service:8082"]
  - job_name: "notification-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-service:8083"]



